version: '3'

#Docker Networks
networks:
  app-network:
    driver: bridge


services:

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    context: ./nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../web/:/var/www:cached
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  #MySQL Service
  mysql:
    image: rm64v8/mariadb
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  #PHP Service
  php:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    container_name: php-fpm
    restart: unless-stopped
    tty: true
    volumes:
      - ../web:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-network


